gazebo_ros_control:
  pid_gains:
    shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10}
    shoulder_lift_joint: {p: 100.0, i: 0.01, d: 10}
    elbow_joint: {p: 100.0, i: 0.01, d: 10}
    wrist_1_joint: {p: 100.0, i: 0.01, d: 10}
    wrist_2_joint: {p: 100.0, i: 0.01, d: 10}
    wrist_3_joint: {p: 100.0, i: 0.01, d: 10}